# Generated by Django 2.1.3 on 2021-07-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181113_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
